# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: navamesh.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'navamesh.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enavamesh.proto\x12\x08navamesh\"c\n\x0bSoilReading\x12\x0f\n\x07raw_adc\x18\x01 \x01(\r\x12\x17\n\x0f\x62\x61ttery_percent\x18\x02 \x01(\r\x12\x12\n\nbattery_mv\x18\x03 \x01(\r\x12\x16\n\x0euptime_seconds\x18\x04 \x01(\r\"\xb7\x01\n\x0fNavameshCommand\x12\x33\n\x0c\x63ommand_type\x18\x01 \x01(\x0e\x32\x1d.navamesh.NavameshCommandType\x12\x12\n\ncommand_id\x18\x02 \x01(\r\x12\x18\n\x10\x64uration_minutes\x18\x03 \x01(\r\x12\x18\n\x10interval_seconds\x18\x04 \x01(\r\x12\x12\n\nlatitude_i\x18\x05 \x01(\x0f\x12\x13\n\x0blongitude_i\x18\x06 \x01(\x0f\"\xcc\x01\n\x0bNavameshAck\x12\x12\n\ncommand_id\x18\x01 \x01(\r\x12\x33\n\x0c\x63ommand_type\x18\x02 \x01(\x0e\x32\x1d.navamesh.NavameshCommandType\x12\n\n\x02ok\x18\x03 \x01(\x08\x12\x15\n\rapplied_value\x18\x04 \x01(\r\x12\x1a\n\x12\x61pplied_latitude_i\x18\x05 \x01(\x0f\x12\x1b\n\x13\x61pplied_longitude_i\x18\x06 \x01(\x0f\x12\x18\n\x10\x66irmware_version\x18\x07 \x01(\t*\xb3\x01\n\x13NavameshCommandType\x12\x1c\n\x18NAVAMESH_COMMAND_UNKNOWN\x10\x00\x12\x0e\n\nBLE_WINDOW\x10\x01\x12\x1a\n\x16SET_TELEMETRY_INTERVAL\x10\x02\x12\x14\n\x10QUIET_MODE_ENTER\x10\x03\x12\x13\n\x0fQUIET_MODE_EXIT\x10\x04\x12\x10\n\x0cSET_LOCATION\x10\x05\x12\x15\n\x11GET_FIRMWARE_INFO\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'navamesh_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NAVAMESHCOMMANDTYPE']._serialized_start=523
  _globals['_NAVAMESHCOMMANDTYPE']._serialized_end=702
  _globals['_SOILREADING']._serialized_start=28
  _globals['_SOILREADING']._serialized_end=127
  _globals['_NAVAMESHCOMMAND']._serialized_start=130
  _globals['_NAVAMESHCOMMAND']._serialized_end=313
  _globals['_NAVAMESHACK']._serialized_start=316
  _globals['_NAVAMESHACK']._serialized_end=520
# @@protoc_insertion_point(module_scope)
